Repository Shivansh-yadav13/SQLite-UI, pull requests merged in 2022-10, with the labels that each got.

#7 fixed the redirect routing
  routes/handlers.go
Labels: Hacktoberfest

#10 test: GitHub workflow added for db tests
  .github/workflows/go.yml
Labels: Hacktoberfest, Hacktoberfest 2022

#20 feat: view table schema
  .gitignore
  db/database.go
  db/database_test.go
  go.mod
  templates/table_view.html
Labels: enhancement, Hacktoberfest, Hacktoberfest 2022

#25 feat: AddColumn function test
  db/database_test.go
Labels: Hacktoberfest, Hacktoberfest 2022

#29 feat: get and view data of a given table with pagination
  db/database.go
  go.mod
  routes/handlers.go
  routes/routes.go
  templates/index.html
  templates/table_data_view.html
Labels: enhancement, Hacktoberfest, Hacktoberfest 2022

#36 feat: tailwindcss
  .gitignore
  README.md
  routes/handlers.go
  routes/routes.go
  static/css/app.css
  static/css/base.css
  static/css/build.min.css
  static/css/styles.css
  tailwind.config.js
  templates/index.html
  templates/setting.html
Labels: enhancement, Hacktoberfest, Hacktoberfest 2022

#41 feat: tweaked the db file path
  .github/workflows/ci.yml
  README.md
  db/database_test.go
  main.go
Labels: enhancement, Hacktoberfest, Hacktoberfest 2022
